#Platform Support
obj-$(CONFIG_SND_LS) +=  ls-i2s.o
obj-$(CONFIG_SND_LS_PCM) +=  ls-pcm.o
obj-$(CONFIG_SND_LS_PCM_GENERIC_DMA) +=  ls-pcm-generic.o

#Machine Support
snd-soc-loongson-es8323-objs := ls-sound.o
obj-$(CONFIG_SND_SOC_LOONGSON_ES8323) += snd-soc-loongson-es8323.o
